version: "3.8"

services:
  cache:
    image: redis:7.4.2-alpine3.21
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - pokedex-network

  db:
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pokemon}
      POSTGRES_USER: ${POSTGRES_USER:-ash}
      POSTGRES_DB: ${POSTGRES_DB:-pokeapi}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-ash}", "-d", "${POSTGRES_DB:-pokeapi}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - pokedex-network

  app:
    build:
      context: ../PokeAPI
      dockerfile: Dockerfile
    user: ${RUN_AS:-pokeapi}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pokemon}
      POSTGRES_USER: ${POSTGRES_USER:-ash}
      POSTGRES_DB: ${POSTGRES_DB:-pokeapi}
    volumes:
      - ../PokeAPI:/code
    links:
      - db
      - cache
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    restart: always
    networks:
      - pokedex-network

  web:
    image: nginx:1.27.3-alpine3.20
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./Resources/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Resources/nginx/ssl:/ssl:ro
      - graphql_cache:/tmp/cache
      - ../dist/browser:/usr/share/nginx/html:ro
    networks:
      - pokedex-network

  graphql-engine:
    image: hasura/graphql-engine:v2.45.1
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER:-ash}:${POSTGRES_PASSWORD:-pokemon}@db:5432/${POSTGRES_DB:-pokeapi}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_LOG_LEVEL: "warn"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET:-pokemon}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anon
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
    networks:
      - pokedex-network

volumes:
  pg_data:
  redis_data:
  graphql_cache:

networks:
  pokedex-network:
    driver: bridge
